name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Build Project
        run: yarn build

      - name: Build Docker image
        run: docker build -t m324-simple-typescript .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/m324-simple-typescript:latest

      - name: Set up kubectl
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Replace and Apply Kubernetes Manifests
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: |
            .k8s/namespace.yml
            .k8s/ui/nuxt-envs.yml
            .k8s/ui/deployment.yml
            .k8s/ui/service.yml
            .k8s/ui/ingress.yml
            .k8s/api/strapi-envs.yml
            .k8s/api/deployment.yml
            .k8s/api/service.yml
            .k8s/api/ingress.yml
          replacement-method: defined