name: CI Workflow

on:
  push:
    branches:
      - dimDev
  pull_request:
    branches:
      - dimDev

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run lint
        run: yarn install

      - name: Run Tests
        run: yarn test

      - name: Build Project
        run: yarn build

      - name: Build Docker image
        run: docker build -t my-app-image .   

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker image
        run: docker tag m324-simple-typescript ${{ secrets.DOCKER_USERNAME }}/m324-simple-typescript:latest

        - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/m324-simple-typescript:latest